/**
 * Seed Script — Categories + Products
 * Run: node utils/seedProducts.js
 *
 * Comprehensive real electrical & hardware shop catalog.
 * Products are named so that the Load Calculator search terms match exactly.
 */
require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('../config/db');
const Category = require('../models/Category');
const Product = require('../models/Product');

const categories = [
  { name: 'Switches & Sockets',      slug: 'switches-sockets',   icon: '🔌', description: 'Modular switches, power sockets and cover plates' },
  { name: 'Wires & Cables',          slug: 'wires-cables',        icon: '🔋', description: 'Copper wires, PVC cables and multi-core cables' },
  { name: 'Fans',                    slug: 'fans',                icon: '🌀', description: 'Ceiling fans, exhaust fans and wall fans' },
  { name: 'Lighting',                slug: 'lighting',            icon: '💡', description: 'LED bulbs, tube lights and panel lights' },
  { name: 'MCB & Distribution',      slug: 'mcb-distribution',    icon: '⚡', description: 'MCBs, distribution boards and RCCBs' },
  { name: 'Conduit & Fittings',      slug: 'conduit-fittings',    icon: '🛠️', description: 'PVC conduit pipes, junction boxes, casing-capping and fittings' },
  { name: 'Tools & Accessories',     slug: 'tools-accessories',   icon: '🔧', description: 'Electrical tools, testers, tapes and accessories' },
  { name: 'UPS & Batteries',         slug: 'ups-batteries',        icon: '🔋', description: 'UPS inverters, tubular batteries, SMF batteries and accessories' },
];

const buildProducts = (cats) => {
  const byCat = {};
  cats.forEach((c) => { byCat[c.slug] = c._id; });

  return [
    // ─────────────────────────────────────────────
    // SWITCHES & SOCKETS
    // ─────────────────────────────────────────────
    {
      name: 'Havells Crabtree 6A One-Way Modular Switch',
      description: 'Havells Crabtree 6A one-way modular switch with superior click feel and a rated life of 100,000 operations. Fire-retardant polycarbonate body. Compatible with all Crabtree modular frames.',
      price: 95,
      category: byCat['switches-sockets'],
      stock: 200,
      brand: 'Havells',
      ratings: 4.5,
      numReviews: 38,
      featured: true,
      isActive: true,
      images: [{ url: '/shop-images/Havells Crabtree 6A One-Way Modular Switch.jpg', public_id: 'seed-1' }],
      specifications: new Map([['Type', 'Modular 1-Way'], ['Rating', '6A / 240V'], ['Color', 'White'], ['Mounting', 'Surface / Flush']]),
    },
    {
      name: 'Anchor Roma 5A One-Way Modular Switch',
      description: 'Anchor Roma 5A one-way modular switch in classic white finish. Ideal for light and fan control. IS 3854 certified, 100,000 cycle life.',
      price: 80,
      category: byCat['switches-sockets'],
      stock: 250,
      brand: 'Anchor',
      ratings: 4.3,
      numReviews: 62,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Anchor Roma 5A One-Way Modular Switch.jpg', public_id: 'seed-2' }],
      specifications: new Map([['Type', 'Modular 1-Way'], ['Rating', '5A / 240V'], ['Color', 'White'], ['Standard', 'IS 3854']]),
    },
    {
      name: 'GM Modular 5A 1-Way Electrical Modular Switch White',
      description: 'GM Modular 5A one-way switch, widely used for light and fan control circuits. Polycarbonate body, flush-mount design, compatible with GM Star modular plates.',
      price: 72,
      category: byCat['switches-sockets'],
      stock: 300,
      brand: 'GM Modular',
      ratings: 4.2,
      numReviews: 45,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/GM Modular 5A 1-Way Electrical Modular Switch White.jpg', public_id: 'seed-3' }],
      specifications: new Map([['Type', 'Modular 1-Way'], ['Rating', '5A / 240V'], ['Color', 'White'], ['Mounting', 'Flush']]),
    },
    {
      name: 'Legrand Mylinc 16A 3-Pin Power Socket Outlet',
      description: 'Legrand Mylinc 16A 3-pin universal power socket outlet with shuttered contacts for child safety. Suitable for AC, refrigerators and washing machines. ISI marked.',
      price: 185,
      category: byCat['switches-sockets'],
      stock: 180,
      brand: 'Legrand',
      ratings: 4.6,
      numReviews: 74,
      featured: true,
      isActive: true,
      images: [{ url: '/shop-images/Legrand Mylinc 16A 3-Pin Power Socket Outlet.jpg', public_id: 'seed-4' }],
      specifications: new Map([['Type', '3-Pin Socket Outlet'], ['Rating', '16A / 240V'], ['Safety', 'Shuttered Contacts'], ['Standard', 'IS 1293']]),
    },
    {
      name: 'Anchor Roma 16A 3-Pin Power Socket Outlet White',
      description: 'Anchor Roma 16A modular 3-pin power socket outlet with child-proof shutters. Ideal for air conditioners, geysers and heavy appliances. Made of fire-retardant polycarbonate.',
      price: 155,
      category: byCat['switches-sockets'],
      stock: 200,
      brand: 'Anchor',
      ratings: 4.4,
      numReviews: 58,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Anchor Roma 16A 3-Pin Power Socket Outlet White.jpg', public_id: 'seed-5' }],
      specifications: new Map([['Type', '3-Pin Socket Outlet'], ['Rating', '16A / 240V'], ['Safety', 'Shuttered'], ['Color', 'White']]),
    },
    {
      name: 'Havells Crabtree 6A 3-Pin Socket Outlet Modular',
      description: 'Havells Crabtree 6A 3-pin modular socket outlet for light appliances. Child-safe shuttered design. Compatible with Crabtree modular series plates.',
      price: 120,
      category: byCat['switches-sockets'],
      stock: 220,
      brand: 'Havells',
      ratings: 4.3,
      numReviews: 41,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Havells Crabtree 6A 3-Pin Socket Outlet Modular.jpg', public_id: 'seed-6' }],
      specifications: new Map([['Type', '3-Pin Socket Outlet'], ['Rating', '6A / 240V'], ['Safety', 'Shuttered'], ['Color', 'White']]),
    },
    {
      name: 'Anchor Roma 6-Module Cover Plate White',
      description: 'Anchor Roma 6-module cover plates in classic white finish. Compatible with all Roma modular accessories. Made of UV-stabilized polycarbonate.',
      price: 180,
      category: byCat['switches-sockets'],
      stock: 150,
      brand: 'Anchor',
      ratings: 4.1,
      numReviews: 27,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Anchor Roma 6-Module Cover Plate White.jpg', public_id: 'seed-7' }],
      specifications: new Map([['Modules', '6'], ['Material', 'Polycarbonate'], ['Color', 'White'], ['Standard', 'IS 3854']]),
    },
    {
      name: 'Legrand Mylinc 8-Module Cover Plate',
      description: 'Legrand Mylinc 8-module flush modular plate for switches and sockets. Compatible with all Mylinc accessories. Ivory/white color.',
      price: 210,
      category: byCat['switches-sockets'],
      stock: 120,
      brand: 'Legrand',
      ratings: 4.3,
      numReviews: 19,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Legrand Mylinc 8-Module Cover Plate.jpg', public_id: 'seed-8' }],
      specifications: new Map([['Modules', '8'], ['Material', 'Polycarbonate'], ['Color', 'White'], ['Brand Series', 'Mylinc']]),
    },

    // ─────────────────────────────────────────────
    // WIRES & CABLES
    // ─────────────────────────────────────────────
    {
      name: 'Polycab Copper Wire 1.0 sq.mm Single Core FR (90m)',
      description: 'Polycab 1.0 sq.mm FR PVC single-core copper wire for light and fan circuits. Excellent conductivity, heat-resistant insulation. ISI marked.',
      price: 560,
      category: byCat['wires-cables'],
      stock: 80,
      brand: 'Polycab',
      ratings: 4.5,
      numReviews: 43,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Polycab Copper Wire 1.0 sq.mm Single Core FR (90m).jpg', public_id: 'seed-9' }],
      specifications: new Map([['Cross Section', '1.0 sq.mm'], ['Length', '90 metres'], ['Insulation', 'FR PVC'], ['Conductor', 'Multi-strand copper']]),
    },
    {
      name: 'Polycab Copper Wire 1.5 sq.mm Single Core FR (90m)',
      description: 'Polycab 1.5 sq.mm FR PVC insulated single-core copper wire. Ideal for domestic wiring, socket circuits and small loads.',
      price: 820,
      category: byCat['wires-cables'],
      stock: 60,
      brand: 'Polycab',
      ratings: 4.7,
      numReviews: 54,
      featured: true,
      isActive: true,
      images: [{ url: '/shop-images/Polycab Copper Wire 1.5 sq.mm Single Core FR (90m).jpg', public_id: 'seed-10' }],
      specifications: new Map([['Cross Section', '1.5 sq.mm'], ['Length', '90 metres'], ['Insulation', 'FR PVC'], ['Conductor', 'Multi-strand copper']]),
    },
    {
      name: 'Polycab Copper Wire 2.5 sq.mm Single Core FR (90m)',
      description: 'Polycab 2.5 sq.mm FR PVC single-core copper wire ideal for AC, refrigerator and power socket circuits. 1100V voltage grade.',
      price: 1260,
      category: byCat['wires-cables'],
      stock: 50,
      brand: 'Polycab',
      ratings: 4.6,
      numReviews: 41,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Polycab Copper Wire 2.5 sq.mm Single Core FR (90m).jpg', public_id: 'seed-11' }],
      specifications: new Map([['Cross Section', '2.5 sq.mm'], ['Length', '90 metres'], ['Insulation', 'FR PVC'], ['Conductor', 'Multi-strand copper']]),
    },
    {
      name: 'Finolex Copper Wire 4.0 sq.mm Single Core FR (90m)',
      description: 'Finolex 4.0 sq.mm FR PVC single-core copper wire for water heaters, high-power appliances and sub-main wiring. Flame-retardant, RoHS compliant.',
      price: 2100,
      category: byCat['wires-cables'],
      stock: 35,
      brand: 'Finolex',
      ratings: 4.6,
      numReviews: 29,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Finolex Copper Wire 4.0 sq.mm Single Core FR (90m).jpg', public_id: 'seed-12' }],
      specifications: new Map([['Cross Section', '4.0 sq.mm'], ['Length', '90 metres'], ['Insulation', 'FR PVC'], ['Voltage Grade', '1100V']]),
    },
    {
      name: 'Havells Copper Wire 6.0 sq.mm Single Core FRLS (90m)',
      description: 'Havells 6.0 sq.mm FRLS PVC single-core copper wire for main feeders and heavy industrial loads. FR + LS (low smoke) insulation for extra safety.',
      price: 3200,
      category: byCat['wires-cables'],
      stock: 20,
      brand: 'Havells',
      ratings: 4.7,
      numReviews: 18,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Havells Copper Wire 6.0 sq.mm Single Core FRLS (90m).jpg', public_id: 'seed-13' }],
      specifications: new Map([['Cross Section', '6.0 sq.mm'], ['Length', '90 metres'], ['Insulation', 'FRLS PVC'], ['Voltage Grade', '1100V']]),
    },
    {
      name: 'Finolex 4 sq.mm 3-Core Flat Cable (100m)',
      description: 'Finolex 4 sq.mm 3-core flat cable for sub-main wiring and power connections. Flame-retardant, RoHS compliant, 1100V rated.',
      price: 3400,
      category: byCat['wires-cables'],
      stock: 25,
      brand: 'Finolex',
      ratings: 4.6,
      numReviews: 29,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Finolex 4 sq.mm 3-Core Flat Cable (100m).jpg', public_id: 'seed-14' }],
      specifications: new Map([['Cross Section', '4 sq.mm'], ['Cores', '3'], ['Length', '100 metres'], ['Voltage Rating', '1100V']]),
    },
    {
      name: 'KEI 2.5 sq.mm 3-Core Flexible Cable (100m)',
      description: 'KEI 3-core flexible cable 2.5 sq.mm for internal wiring extensions and sub-circuits. PVC insulated copper conductor.',
      price: 2200,
      category: byCat['wires-cables'],
      stock: 30,
      brand: 'KEI',
      ratings: 4.4,
      numReviews: 22,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/KEI 2.5 sq.mm 3-Core Flexible Cable (100m).jpg', public_id: 'seed-15' }],
      specifications: new Map([['Cross Section', '2.5 sq.mm'], ['Cores', '3'], ['Length', '100 metres'], ['Type', 'Flexible']]),
    },

    // ─────────────────────────────────────────────
    // FANS
    // ─────────────────────────────────────────────
    {
      name: 'Crompton Aura Prime 1200mm High-Speed Ceiling Fan',
      description: 'Crompton Aura Prime 1200mm ceiling fan with high-speed motor. Delivers 220 CMM air delivery with rust-proof aluminium blades. Suitable for medium to large rooms.',
      price: 1450,
      category: byCat['fans'],
      stock: 40,
      brand: 'Crompton',
      ratings: 4.3,
      numReviews: 88,
      featured: true,
      isActive: true,
      images: [{ url: '/shop-images/Crompton Aura Prime 1200mm High-Speed Ceiling Fan.jpg', public_id: 'seed-16' }],
      specifications: new Map([['Sweep', '1200mm'], ['Power', '75W'], ['Speed', '350 RPM'], ['Air Delivery', '220 CMM']]),
    },
    {
      name: 'Havells Stealth 1200mm BLDC Ceiling Fan with Remote',
      description: 'Havells Stealth BLDC 1200mm ceiling fan with remote control. Consumes only 28W, saves up to 65% energy. 5-speed control and sleep mode.',
      price: 3799,
      category: byCat['fans'],
      stock: 25,
      brand: 'Havells',
      ratings: 4.6,
      numReviews: 73,
      featured: true,
      isActive: true,
      images: [{ url: '/shop-images/Havells Stealth 1200mm BLDC Ceiling Fan with Remote.jpg', public_id: 'seed-17' }],
      specifications: new Map([['Sweep', '1200mm'], ['Power', '28W (BLDC)'], ['Speed', '350 RPM'], ['Remote', 'Included']]),
    },
    {
      name: 'Orient Electric Apex-FX 1200mm BLDC Ceiling Fan',
      description: 'Orient Electric Apex-FX 1200mm BLDC ceiling fan. IoT-ready remote control. Saves up to 65% energy vs conventional fans.',
      price: 4999,
      category: byCat['fans'],
      stock: 20,
      brand: 'Orient Electric',
      ratings: 4.7,
      numReviews: 52,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Orient Electric Apex-FX 1200mm BLDC Ceiling Fan.jpg', public_id: 'seed-18' }],
      specifications: new Map([['Sweep', '1200mm'], ['Power', '25W (BLDC)'], ['Speed', '360 RPM'], ['Remote', 'Included']]),
    },
    {
      name: 'Bajaj Midea 250mm Exhaust Fan for Kitchen & Bathroom',
      description: 'Bajaj Midea 250mm exhaust fan for kitchens, bathrooms and small rooms. High air suction, low noise, dust-resistant shutter blade.',
      price: 1099,
      category: byCat['fans'],
      stock: 45,
      brand: 'Bajaj',
      ratings: 4.1,
      numReviews: 33,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Bajaj Midea 250mm Exhaust Fan for Kitchen & Bathroom.jpg', public_id: 'seed-19' }],
      specifications: new Map([['Blade Size', '250mm'], ['Power', '30W'], ['Voltage', '230V / 50Hz'], ['Speed', '1350 RPM']]),
    },
    {
      name: 'Havells Ventilair 300mm Exhaust Fan',
      description: 'Havells Ventilair 300mm exhaust fan with high-efficiency motor and low noise operation. Suitable for kitchens, bathrooms and utility rooms.',
      price: 1350,
      category: byCat['fans'],
      stock: 35,
      brand: 'Havells',
      ratings: 4.3,
      numReviews: 27,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Havells Ventilair 300mm Exhaust Fan.jpg', public_id: 'seed-20' }],
      specifications: new Map([['Blade Size', '300mm'], ['Power', '35W'], ['Voltage', '230V / 50Hz'], ['Speed', '1280 RPM']]),
    },
    {
      name: 'Crompton Pedestal Fan 400mm High-Speed',
      description: 'Crompton 400mm pedestal fan with 3-speed control and oscillation. Ideal for offices and large rooms. Rust-free aluminium blades.',
      price: 2100,
      category: byCat['fans'],
      stock: 18,
      brand: 'Crompton',
      ratings: 4.2,
      numReviews: 41,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Crompton Pedestal Fan 400mm High-Speed.jpg', public_id: 'seed-21' }],
      specifications: new Map([['Sweep', '400mm'], ['Power', '105W'], ['Speeds', '3'], ['Oscillation', 'Yes']]),
    },

    // ─────────────────────────────────────────────
    // LIGHTING
    // ─────────────────────────────────────────────
    {
      name: 'Philips Stellar Bright 9W LED Bulb B22 (Pack of 4)',
      description: 'Philips 9W LED bulb with 950 lumens output. Replaces 60W incandescent. 6500K cool daylight, 2-year warranty.',
      price: 399,
      category: byCat['lighting'],
      stock: 200,
      brand: 'Philips',
      ratings: 4.6,
      numReviews: 112,
      featured: true,
      isActive: true,
      images: [{ url: '/shop-images/Philips Stellar Bright 9W LED Bulb B22 (Pack of 4).jpg', public_id: 'seed-22' }],
      specifications: new Map([['Wattage', '9W'], ['Lumens', '950 lm'], ['Color Temp', '6500K'], ['Life', '15,000 hours']]),
    },
    {
      name: 'Syska Base B22 7W LED Bulb (Pack of 6)',
      description: 'Syska 7W LED bulb with 700 lumens for general lighting. B22 base. Energy saving, long 25,000-hour rated life.',
      price: 359,
      category: byCat['lighting'],
      stock: 180,
      brand: 'Syska',
      ratings: 4.3,
      numReviews: 87,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Syska Base B22 7W LED Bulb (Pack of 6).jpg', public_id: 'seed-23' }],
      specifications: new Map([['Wattage', '7W'], ['Lumens', '700 lm'], ['Base', 'B22'], ['Life', '25,000 hours']]),
    },
    {
      name: 'Syska T5 18W LED Tube Light 4ft (Pack of 2)',
      description: 'Syska 18W integrated LED tube light with aluminium body and milky diffuser. Instant start, flicker-free.',
      price: 485,
      category: byCat['lighting'],
      stock: 95,
      brand: 'Syska',
      ratings: 4.3,
      numReviews: 44,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Syska T5 18W LED Tube Light 4ft (Pack of 2).jpg', public_id: 'seed-24' }],
      specifications: new Map([['Wattage', '18W'], ['Length', '1200mm (4ft)'], ['Lumens', '1800 lm'], ['IP Rating', 'IP20']]),
    },
    {
      name: 'Wipro Garnet 20W LED Panel Light Round Surface',
      description: 'Wipro 20W round surface-mount LED panel light with slim design. 1800 lumens, 6500K cool white. Ideal for living rooms and offices.',
      price: 650,
      category: byCat['lighting'],
      stock: 70,
      brand: 'Wipro',
      ratings: 4.4,
      numReviews: 55,
      featured: true,
      isActive: true,
      images: [{ url: '/shop-images/Wipro Garnet 20W LED Panel Light Round Surface.jpg', public_id: 'seed-25' }],
      specifications: new Map([['Wattage', '20W'], ['Lumens', '1800 lm'], ['Color Temp', '6500K'], ['Type', 'Round Surface']]),
    },
    {
      name: 'Orient Electric 12W LED Downlight Recessed',
      description: 'Orient Electric 12W recessed LED downlight with aluminum body and anti-glare diffuser. Suitable for false ceilings.',
      price: 420,
      category: byCat['lighting'],
      stock: 85,
      brand: 'Orient Electric',
      ratings: 4.2,
      numReviews: 38,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Orient Electric 12W LED Downlight Recessed.jpg', public_id: 'seed-26' }],
      specifications: new Map([['Wattage', '12W'], ['Type', 'Recessed Downlight'], ['Color Temp', '4000K Neutral White'], ['Cutout', '125mm']]),
    },
    {
      name: 'Havells 36W LED Batten Light 4ft Surface Mount',
      description: 'Havells 36W LED batten light for surface mounting. 3600 lumens, cool white 6500K. Flicker-free, ideal for kitchens, garages and corridors.',
      price: 780,
      category: byCat['lighting'],
      stock: 60,
      brand: 'Havells',
      ratings: 4.5,
      numReviews: 49,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Havells 36W LED Batten Light 4ft Surface Mount.jpg', public_id: 'seed-27' }],
      specifications: new Map([['Wattage', '36W'], ['Lumens', '3600 lm'], ['Color Temp', '6500K'], ['Length', '1200mm']]),
    },

    // ─────────────────────────────────────────────
    // MCB & DISTRIBUTION
    // ─────────────────────────────────────────────
    {
      name: 'Legrand 6A Single-Pole MCB C-Curve Circuit Breaker',
      description: 'Legrand 6A SP MCB C-Curve for light and fan sub-circuits. IEC 60898 compliant, 6kA breaking capacity. DIN rail mount.',
      price: 210,
      category: byCat['mcb-distribution'],
      stock: 100,
      brand: 'Legrand',
      ratings: 4.6,
      numReviews: 34,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Legrand 6A Single-Pole MCB C-Curve Circuit Breaker.jpg', public_id: 'seed-28' }],
      specifications: new Map([['Rating', '6A'], ['Poles', '1 (Single)'], ['Curve', 'C-Curve'], ['Breaking Capacity', '6kA']]),
    },
    {
      name: 'Legrand 10A Single-Pole MCB C-Curve Circuit Breaker',
      description: 'Legrand 10A SP MCB C-Curve for socket and power sub-circuits. IEC 60898, 6kA breaking capacity.',
      price: 240,
      category: byCat['mcb-distribution'],
      stock: 90,
      brand: 'Legrand',
      ratings: 4.6,
      numReviews: 29,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Legrand 10A Single-Pole MCB C-Curve Circuit Breaker.jpg', public_id: 'seed-29' }],
      specifications: new Map([['Rating', '10A'], ['Poles', '1 (Single)'], ['Curve', 'C-Curve'], ['Breaking Capacity', '6kA']]),
    },
    {
      name: 'Legrand 16A Single-Pole MCB C-Curve Circuit Breaker',
      description: 'Legrand 16A SP MCB C-Curve for residential and light commercial wiring. IEC 60898, 6kA breaking capacity.',
      price: 320,
      category: byCat['mcb-distribution'],
      stock: 70,
      brand: 'Legrand',
      ratings: 4.7,
      numReviews: 58,
      featured: true,
      isActive: true,
      images: [{ url: '/shop-images/Legrand 16A Single-Pole MCB C-Curve Circuit Breaker.jpg', public_id: 'seed-30' }],
      specifications: new Map([['Rating', '16A'], ['Poles', '1 (Single)'], ['Curve', 'C-Curve'], ['Breaking Capacity', '6kA']]),
    },
    {
      name: 'Legrand 20A Single-Pole MCB C-Curve Circuit Breaker',
      description: 'Legrand 20A SP MCB C-Curve for AC and heavy appliance circuits. IEC 60898, 6kA breaking capacity.',
      price: 360,
      category: byCat['mcb-distribution'],
      stock: 60,
      brand: 'Legrand',
      ratings: 4.6,
      numReviews: 22,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Legrand 20A Single-Pole MCB C-Curve Circuit Breaker.jpg', public_id: 'seed-31' }],
      specifications: new Map([['Rating', '20A'], ['Poles', '1 (Single)'], ['Curve', 'C-Curve'], ['Breaking Capacity', '6kA']]),
    },
    {
      name: 'Legrand 25A Single-Pole MCB C-Curve Circuit Breaker',
      description: 'Legrand 25A SP MCB C-Curve for water heater and heavy appliance circuits. IEC 60898, 6kA breaking capacity.',
      price: 410,
      category: byCat['mcb-distribution'],
      stock: 50,
      brand: 'Legrand',
      ratings: 4.6,
      numReviews: 17,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Legrand 25A Single-Pole MCB C-Curve Circuit Breaker.jpg', public_id: 'seed-32' }],
      specifications: new Map([['Rating', '25A'], ['Poles', '1 (Single)'], ['Curve', 'C-Curve'], ['Breaking Capacity', '6kA']]),
    },
    {
      name: 'Legrand 32A Single-Pole MCB C-Curve Circuit Breaker',
      description: 'Legrand 32A SP MCB C-Curve for sub-main and heavy circuits. IEC 60898, 6kA breaking capacity.',
      price: 460,
      category: byCat['mcb-distribution'],
      stock: 40,
      brand: 'Legrand',
      ratings: 4.7,
      numReviews: 14,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Legrand 32A Single-Pole MCB C-Curve Circuit Breaker.jpg', public_id: 'seed-33' }],
      specifications: new Map([['Rating', '32A'], ['Poles', '1 (Single)'], ['Curve', 'C-Curve'], ['Breaking Capacity', '6kA']]),
    },
    {
      name: 'Havells 40A DP MCB C-Curve Double Pole Circuit Breaker',
      description: 'Havells 40A double-pole MCB C-Curve for main circuit protection. IEC 60898, 10kA breaking capacity.',
      price: 980,
      category: byCat['mcb-distribution'],
      stock: 30,
      brand: 'Havells',
      ratings: 4.7,
      numReviews: 21,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Havells 40A DP MCB C-Curve Double Pole Circuit Breaker.jpg', public_id: 'seed-34' }],
      specifications: new Map([['Rating', '40A'], ['Poles', '2 (Double)'], ['Curve', 'C-Curve'], ['Breaking Capacity', '10kA']]),
    },
    {
      name: 'Schneider Acti9 8-Way MCB Distribution Board DB Box Single Phase',
      description: 'Schneider Acti9 8-way single-phase distribution board DB box with double door. IP30, DIN rail for MCB mounting. Pre-wired neutral bar. Ideal for residential wiring.',
      price: 2850,
      category: byCat['mcb-distribution'],
      stock: 18,
      brand: 'Schneider Electric',
      ratings: 4.8,
      numReviews: 23,
      featured: true,
      isActive: true,
      images: [{ url: '/shop-images/Schneider Acti9 8-Way MCB Distribution Board DB Box Single Phase.jpg', public_id: 'seed-35' }],
      specifications: new Map([['Ways', '8'], ['Phase', 'Single Phase'], ['IP Rating', 'IP30'], ['Standard', 'IEC 61439-3']]),
    },
    {
      name: 'Legrand 12-Way MCB Distribution Board DB Box Single Phase',
      description: 'Legrand 12-way single-phase MCB distribution board with DIN rail. IP30 protection, pre-wired earth and neutral bars. Suitable for apartments and small offices.',
      price: 3200,
      category: byCat['mcb-distribution'],
      stock: 12,
      brand: 'Legrand',
      ratings: 4.7,
      numReviews: 16,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Legrand 12-Way MCB Distribution Board DB Box Single Phase.jpg', public_id: 'seed-36' }],
      specifications: new Map([['Ways', '12'], ['Phase', 'Single Phase'], ['IP Rating', 'IP30'], ['Standard', 'IEC 61439-3']]),
    },
    {
      name: 'Havells 32A DP RCCB 30mA Residual Current Circuit Breaker',
      description: 'Havells 32A Double Pole RCCB with 30mA sensitivity. Residual current circuit breaker for earth-leakage protection. High immunity to nuisance tripping. IS 12640 certified.',
      price: 980,
      category: byCat['mcb-distribution'],
      stock: 40,
      brand: 'Havells',
      ratings: 4.5,
      numReviews: 31,
      featured: true,
      isActive: true,
      images: [{ url: '/shop-images/Havells 32A DP RCCB 30mA Residual Current Circuit Breaker.jpg', public_id: 'seed-37' }],
      specifications: new Map([['Rating', '32A'], ['Poles', 'Double Pole'], ['Sensitivity', '30mA'], ['Standard', 'IS 12640']]),
    },
    {
      name: 'Legrand 25A DP RCCB 30mA Residual Current Circuit Breaker',
      description: 'Legrand 25A double-pole RCCB 30mA sensitivity. Residual current circuit breaker for shock and leakage protection. IEC 61008-1 certified.',
      price: 850,
      category: byCat['mcb-distribution'],
      stock: 35,
      brand: 'Legrand',
      ratings: 4.5,
      numReviews: 19,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Legrand 25A DP RCCB 30mA Residual Current Circuit Breaker.jpg', public_id: 'seed-38' }],
      specifications: new Map([['Rating', '25A'], ['Poles', 'Double Pole'], ['Sensitivity', '30mA'], ['Standard', 'IEC 61008-1']]),
    },

    // ─────────────────────────────────────────────
    // CONDUIT & FITTINGS
    // ─────────────────────────────────────────────
    {
      name: 'Astral PVC Conduit Pipe 20mm ISI (3m) — Pack of 10',
      description: 'Astral ISI-marked 20mm rigid PVC electrical conduit pipe for wire protection and routing in walls and ceilings. 3m length, pack of 10 pipes (30m total). Flame-retardant, impact-resistant.',
      price: 620,
      category: byCat['conduit-fittings'],
      stock: 90,
      brand: 'Astral',
      ratings: 4.4,
      numReviews: 47,
      featured: true,
      isActive: true,
      images: [{ url: '/shop-images/Astral PVC Conduit Pipe 20mm ISI (3m) — Pack of 10.jpg', public_id: 'seed-39' }],
      specifications: new Map([['Diameter', '20mm'], ['Length', '3m per pipe (30m pack)'], ['Material', 'Rigid PVC'], ['Standard', 'IS 14930']]),
    },
    {
      name: 'Supreme PVC Electrical Conduit Pipe 20mm (3m)',
      description: 'Supreme 20mm rigid PVC electrical conduit pipe for concealed and surface wiring. Flame-retardant, high-impact strength. IS 14930 certified.',
      price: 65,
      category: byCat['conduit-fittings'],
      stock: 300,
      brand: 'Supreme',
      ratings: 4.3,
      numReviews: 62,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Supreme PVC Electrical Conduit Pipe 20mm (3m).jpg', public_id: 'seed-40' }],
      specifications: new Map([['Diameter', '20mm'], ['Length', '3 metres'], ['Material', 'Rigid PVC'], ['Standard', 'IS 14930']]),
    },
    {
      name: 'Finolex PVC Conduit Pipe 25mm (3m)',
      description: 'Finolex 25mm rigid PVC electrical conduit pipe for heavier cable runs. Flame-retardant, UV-resistant. 3m length.',
      price: 85,
      category: byCat['conduit-fittings'],
      stock: 200,
      brand: 'Finolex',
      ratings: 4.4,
      numReviews: 33,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Finolex PVC Conduit Pipe 25mm (3m).jpg', public_id: 'seed-41' }],
      specifications: new Map([['Diameter', '25mm'], ['Length', '3 metres'], ['Material', 'Rigid PVC'], ['Standard', 'IS 14930']]),
    },
    {
      name: 'Anchor PVC Electrical Junction Box 4x4 Inch Surface Mount',
      description: 'Anchor 4x4 inch PVC electrical junction box for wire connections and splicing. Surface mount or flush mount. Flame-retardant polycarbonate, dust-proof lid.',
      price: 45,
      category: byCat['conduit-fittings'],
      stock: 400,
      brand: 'Anchor',
      ratings: 4.2,
      numReviews: 78,
      featured: true,
      isActive: true,
      images: [{ url: '/shop-images/Anchor PVC Electrical Junction Box 4x4 Inch Surface Mount.jpg', public_id: 'seed-42' }],
      specifications: new Map([['Size', '4x4 inch'], ['Material', 'PVC / Polycarbonate'], ['Mount', 'Surface / Flush'], ['IP Rating', 'IP40']]),
    },
    {
      name: 'Legrand Electrical Junction Box 3x3 Inch PVC',
      description: 'Legrand 3x3 inch PVC junction box for branching wire connections. Flame-retardant body, screw-on or snap-fit lid. Suitable for conduit wiring systems.',
      price: 35,
      category: byCat['conduit-fittings'],
      stock: 500,
      brand: 'Legrand',
      ratings: 4.3,
      numReviews: 55,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Legrand Electrical Junction Box 3x3 Inch PVC.jpg', public_id: 'seed-43' }],
      specifications: new Map([['Size', '3x3 inch'], ['Material', 'PVC'], ['Mount', 'Surface / Flush'], ['Color', 'White']]),
    },
    {
      name: 'GM Modular PVC Electrical Junction Box 2x2 Inch',
      description: 'GM Modular 2x2 inch PVC junction box for wire junction points in concealed and surface conduit wiring. Flame-retardant, easy screw lid.',
      price: 28,
      category: byCat['conduit-fittings'],
      stock: 600,
      brand: 'GM Modular',
      ratings: 4.1,
      numReviews: 41,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/GM Modular PVC Electrical Junction Box 2x2 Inch.jpg', public_id: 'seed-44' }],
      specifications: new Map([['Size', '2x2 inch'], ['Material', 'PVC'], ['Color', 'White'], ['Mount', 'Surface']]),
    },
    {
      name: 'Anchor Casing-Capping PVC 1 inch x 100ft White',
      description: 'Anchor PVC casing-capping for surface wiring. 1 inch wide, 100ft roll, white. Flame-retardant, UV-stabilised. Includes matching caps.',
      price: 280,
      category: byCat['conduit-fittings'],
      stock: 110,
      brand: 'Anchor',
      ratings: 4.0,
      numReviews: 18,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Anchor Casing-Capping PVC 1 inch x 100ft White.jpg', public_id: 'seed-45' }],
      specifications: new Map([['Width', '1 inch'], ['Length', '100 ft'], ['Material', 'PVC'], ['Color', 'White']]),
    },
    {
      name: 'Astral PVC Conduit Elbow 20mm 90-Degree (Pack of 10)',
      description: 'Astral 20mm 90-degree PVC conduit elbow for turning wire conduit runs at right angles. Flame-retardant. Pack of 10 pieces.',
      price: 90,
      category: byCat['conduit-fittings'],
      stock: 250,
      brand: 'Astral',
      ratings: 4.1,
      numReviews: 22,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Astral PVC Conduit Elbow 20mm 90-Degree (Pack of 10).jpg', public_id: 'seed-46' }],
      specifications: new Map([['Diameter', '20mm'], ['Angle', '90 degrees'], ['Material', 'PVC'], ['Pack', '10 pieces']]),
    },
    {
      name: 'Galvanized Steel Electrical Junction Box 4x4 Inch',
      description: 'Heavy-duty galvanized steel junction box 4x4 inch for industrial and outdoor applications. IP55 rated, rust-proof coating.',
      price: 120,
      category: byCat['conduit-fittings'],
      stock: 150,
      brand: 'Generic',
      ratings: 4.3,
      numReviews: 29,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Galvanized Steel Electrical Junction Box 4x4 Inch.jpg', public_id: 'seed-47' }],
      specifications: new Map([['Size', '4x4 inch'], ['Material', 'Galvanized Steel'], ['IP Rating', 'IP55'], ['Use', 'Industrial / Outdoor']]),
    },

    // ─────────────────────────────────────────────
    // TOOLS & ACCESSORIES
    // ─────────────────────────────────────────────
    {
      name: 'Stanley FatMax Electrical Tester Screwdriver Set 6-Piece',
      description: 'Stanley 6-piece electrical tester and screwdriver set with VDE-rated insulation up to 1000V AC. Neon voltage tester included for quick circuit checks.',
      price: 649,
      category: byCat['tools-accessories'],
      stock: 55,
      brand: 'Stanley',
      ratings: 4.4,
      numReviews: 76,
      featured: true,
      isActive: true,
      images: [{ url: '/shop-images/Stanley FatMax Electrical Tester Screwdriver Set 6-Piece.jpg', public_id: 'seed-48' }],
      specifications: new Map([['Pieces', '6'], ['Insulation', 'VDE 1000V'], ['Handle', 'Bi-material CushionGrip'], ['Includes', 'Voltage Tester']]),
    },
    {
      name: 'Fluke 101 Basic Digital Multimeter',
      description: 'Fluke 101 basic digital multimeter for AC/DC voltage, resistance and continuity testing. Auto-ranging, 600V CAT III safety rating.',
      price: 2100,
      category: byCat['tools-accessories'],
      stock: 22,
      brand: 'Fluke',
      ratings: 4.8,
      numReviews: 63,
      featured: true,
      isActive: true,
      images: [{ url: '/shop-images/Fluke 101 Basic Digital Multimeter.jpg', public_id: 'seed-49' }],
      specifications: new Map([['Type', 'Digital Multimeter'], ['Voltage Range', 'AC/DC 600V'], ['Safety', 'CAT III 600V'], ['Display', '4000 count']]),
    },
    {
      name: 'Mastech MS8268 Auto-Range Digital Multimeter',
      description: 'Mastech MS8268 auto-range digital multimeter with AC/DC voltage, current, resistance, capacitance and frequency measurement.',
      price: 1450,
      category: byCat['tools-accessories'],
      stock: 30,
      brand: 'Mastech',
      ratings: 4.5,
      numReviews: 44,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Mastech MS8268 Auto-Range Digital Multimeter.jpg', public_id: 'seed-50' }],
      specifications: new Map([['Type', 'Auto-Range Multimeter'], ['Voltage Range', 'AC/DC 750V'], ['Safety', 'CAT III 600V'], ['Features', 'Capacitance, Frequency']]),
    },
    {
      name: '3M Scotch 33+ Electrical Insulation Tape 19mm x 20m (Pack of 5)',
      description: '3M Scotch 33+ premium vinyl electrical insulation tape. UV-resistant, water-proof, rated 600V, -18°C to 105°C operating range. Pack of 5 rolls.',
      price: 320,
      category: byCat['tools-accessories'],
      stock: 200,
      brand: '3M',
      ratings: 4.7,
      numReviews: 92,
      featured: true,
      isActive: true,
      images: [{ url: '/shop-images/3M Scotch 33+ Electrical Insulation Tape 19mm x 20m (Pack of 5).jpg', public_id: 'seed-51' }],
      specifications: new Map([['Width', '19mm'], ['Length', '20m per roll'], ['Rating', '600V / 105°C'], ['Pack', '5 rolls']]),
    },
    {
      name: 'Bosch GSR 185-LI Cordless Drill Driver',
      description: 'Bosch GSR 185-LI 18V cordless drill driver with 2Ah battery. 25+1 torque settings, 2-speed gearbox, LED work light. Ideal for electricians and contractors.',
      price: 6500,
      category: byCat['tools-accessories'],
      stock: 12,
      brand: 'Bosch',
      ratings: 4.7,
      numReviews: 59,
      featured: true,
      isActive: true,
      images: [{ url: '/shop-images/Bosch GSR 185-LI Cordless Drill Driver.jpg', public_id: 'seed-52' }],
      specifications: new Map([['Voltage', '18V Lithium-ion'], ['Speed', '2-speed gearbox'], ['Torque Settings', '25+1'], ['Battery', '2Ah']]),
    },
    {
      name: 'Taparia Wire Stripper & Cutter Pliers',
      description: 'Taparia professional wire stripper and cutter combination pliers. Strips 1.0–4.0mm wire, cuts cables up to 6mm. Insulated handles 1000V VDE.',
      price: 480,
      category: byCat['tools-accessories'],
      stock: 65,
      brand: 'Taparia',
      ratings: 4.4,
      numReviews: 51,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Taparia Wire Stripper & Cutter Pliers.jpg', public_id: 'seed-53' }],
      specifications: new Map([['Type', 'Wire Stripper & Cutter'], ['Range', '1.0–4.0mm'], ['Insulation', 'VDE 1000V'], ['Material', 'Chrome-Vanadium']]),
    },
    {
      name: 'Camsco Non-Contact Voltage Tester Pen',
      description: 'Camsco non-contact AC voltage tester pen for 90V–1000V AC. LED and buzzer indication. Safe, no direct contact needed.',
      price: 280,
      category: byCat['tools-accessories'],
      stock: 80,
      brand: 'Camsco',
      ratings: 4.3,
      numReviews: 67,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Camsco Non-Contact Voltage Tester Pen.jpg', public_id: 'seed-54' }],
      specifications: new Map([['Type', 'Non-Contact Voltage Tester'], ['Range', '90–1000V AC'], ['Indication', 'LED + Buzzer'], ['Form Factor', 'Pen']]),
    },
    {
      name: 'Finolex Cable Tie 100mm x 2.5mm (Pack of 100)',
      description: 'Finolex nylon cable ties 100mm x 2.5mm for bundling wires and cables. UV-stabilised, tensile strength 8kg. Pack of 100 pieces.',
      price: 120,
      category: byCat['tools-accessories'],
      stock: 300,
      brand: 'Finolex',
      ratings: 4.2,
      numReviews: 38,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Finolex Cable Tie 100mm x 2.5mm (Pack of 100).jpg', public_id: 'seed-55' }],
      specifications: new Map([['Size', '100mm x 2.5mm'], ['Material', 'Nylon 66'], ['Tensile Strength', '8kg'], ['Pack', '100 pieces']]),
    },

    // ─────────────────────────────────────────────
    // UPS & BATTERIES
    // ─────────────────────────────────────────────
    {
      name: 'Amaron 150Ah Tall Tubular Battery',
      description: 'Amaron Tall Tubular 150Ah inverter battery with advanced paste technology for long backup time. Suitable for frequent power-cut areas. Low maintenance with superior charge acceptance.',
      price: 13500,
      category: byCat['ups-batteries'],
      stock: 30,
      brand: 'Amaron',
      ratings: 4.6,
      numReviews: 52,
      featured: true,
      isActive: true,
      images: [{ url: '/shop-images/Amaron 150Ah Tall Tubular Battery.jpg', public_id: 'seed-56' }],
      specifications: new Map([['Type', 'Tall Tubular'], ['Capacity', '150Ah / 12V'], ['Warranty', '60 Months'], ['Technology', 'Tubular Plate']]),
    },
    {
      name: 'Exide Inva Tubular 150Ah Battery',
      description: 'Exide InvaTubular 150Ah battery with high purity spine alloy for extended service life. Ideal for home UPS and inverter systems in medium to heavy load conditions.',
      price: 14200,
      category: byCat['ups-batteries'],
      stock: 25,
      brand: 'Exide',
      ratings: 4.5,
      numReviews: 67,
      featured: true,
      isActive: true,
      images: [{ url: '/shop-images/Exide Inva Tubular 150Ah Battery.jpg', public_id: 'seed-57' }],
      specifications: new Map([['Type', 'Tall Tubular'], ['Capacity', '150Ah / 12V'], ['Warranty', '60 Months'], ['Standard', 'IS 15549']]),
    },
    {
      name: 'Luminous Red Charge RC 18000 150Ah Battery',
      description: 'Luminous Red Charge 150Ah tall tubular battery with high charge acceptance for fast recharge. Designed for long power cuts. Corrosion-resistant alloy spines for durability.',
      price: 13800,
      category: byCat['ups-batteries'],
      stock: 28,
      brand: 'Luminous',
      ratings: 4.7,
      numReviews: 89,
      featured: true,
      isActive: true,
      images: [{ url: '/shop-images/Luminous Red Charge RC 18000 150Ah Battery.jpg', public_id: 'seed-58' }],
      specifications: new Map([['Type', 'Tall Tubular'], ['Capacity', '150Ah / 12V'], ['Warranty', '60 Months'], ['Series', 'Red Charge']]),
    },
    {
      name: 'Exide Inva Tubular 100Ah Battery',
      description: 'Exide InvaTubular 100Ah flat-plate tubular battery suitable for small homes and light loads. Reliable backup for fans, lights and small appliances.',
      price: 9800,
      category: byCat['ups-batteries'],
      stock: 35,
      brand: 'Exide',
      ratings: 4.4,
      numReviews: 44,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Exide Inva Tubular 100Ah Battery.jpg', public_id: 'seed-59' }],
      specifications: new Map([['Type', 'Tall Tubular'], ['Capacity', '100Ah / 12V'], ['Warranty', '48 Months'], ['Standard', 'IS 15549']]),
    },
    {
      name: 'APC Back-UPS BX600C 600VA UPS',
      description: 'APC Back-UPS 600VA / 360W UPS with AVR for computers, modems and networking devices. 6 outlets, surge-protected sockets, display for battery and load status.',
      price: 4500,
      category: byCat['ups-batteries'],
      stock: 40,
      brand: 'APC',
      ratings: 4.5,
      numReviews: 73,
      featured: true,
      isActive: true,
      images: [{ url: '/shop-images/APC Back-UPS BX600C 600VA UPS.jpg', public_id: 'seed-60' }],
      specifications: new Map([['Type', 'Offline UPS'], ['Capacity', '600VA / 360W'], ['Input Voltage', '230V'], ['Outlets', '6']]),
    },
    {
      name: 'Luminous Eco Volt Neo 1050 900VA UPS',
      description: 'Luminous Eco Volt Neo 1050 home UPS with intelligent battery management for extended battery life. Supports tubular batteries up to 180Ah. Pure sine wave output suitable for all loads.',
      price: 6200,
      category: byCat['ups-batteries'],
      stock: 22,
      brand: 'Luminous',
      ratings: 4.6,
      numReviews: 95,
      featured: true,
      isActive: true,
      images: [{ url: '/shop-images/Luminous Eco Volt Neo 1050 900VA UPS.jpg', public_id: 'seed-61' }],
      specifications: new Map([['Type', 'Home UPS / Inverter'], ['Capacity', '900VA / 756W'], ['Output', 'Pure Sine Wave'], ['Battery Support', 'Up to 180Ah']]),
    },
    {
      name: 'Microtek UPS EB 900VA Home Inverter',
      description: 'Microtek UPS EB 900VA digital inverter with automatic voltage regulation. Supports 1 battery (12V). Ideal for small homes — powers lights, fans and mobile chargers.',
      price: 5500,
      category: byCat['ups-batteries'],
      stock: 20,
      brand: 'Microtek',
      ratings: 4.3,
      numReviews: 61,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Microtek UPS EB 900VA Home Inverter.jpg', public_id: 'seed-62' }],
      specifications: new Map([['Type', 'Home Inverter'], ['Capacity', '900VA'], ['Output', 'Modified Sine Wave'], ['Battery', '1 × 12V']]),
    },
    {
      name: 'Amaron 12V 7Ah SMF VRLA Battery',
      description: 'Amaron sealed maintenance-free (SMF) VRLA 12V 7Ah battery for UPS, alarm systems and emergency lighting. Spill-proof, leak-proof design. Rechargeable and long shelf life.',
      price: 950,
      category: byCat['ups-batteries'],
      stock: 80,
      brand: 'Amaron',
      ratings: 4.4,
      numReviews: 36,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Amaron 12V 7Ah SMF VRLA Battery.jpg', public_id: 'seed-63' }],
      specifications: new Map([['Type', 'SMF / VRLA'], ['Voltage', '12V'], ['Capacity', '7Ah'], ['Technology', 'AGM']]),
    },
    {
      name: 'Exide 12V 42Ah SMF Battery',
      description: 'Exide sealed maintenance-free battery 12V 42Ah suitable for medium-capacity UPS systems, security systems and solar applications. Zero maintenance, vibration-resistant.',
      price: 3800,
      category: byCat['ups-batteries'],
      stock: 45,
      brand: 'Exide',
      ratings: 4.3,
      numReviews: 29,
      featured: false,
      isActive: true,
      images: [{ url: '/shop-images/Exide 12V 42Ah SMF Battery.jpg', public_id: 'seed-64' }],
      specifications: new Map([['Type', 'SMF / VRLA'], ['Voltage', '12V'], ['Capacity', '42Ah'], ['Standard', 'IS 16270']]),
    },
  ];
};

const seed = async () => {
  try {
    await connectDB();
    console.log('\n🌱 Starting seed...');

    // Clear existing seed data (keep user-created data)
    await Category.deleteMany({});
    console.log('✔ Cleared categories');

    const createdCats = await Category.insertMany(categories);
    console.log(`✔ Created ${createdCats.length} categories`);

    // Remove ALL existing products to start fresh
    await Product.deleteMany({});
    console.log('✔ Cleared products');

    const products = buildProducts(createdCats);
    await Product.insertMany(products);
    console.log(`✔ Inserted ${products.length} products`);

    console.log('\n✅ Seed complete!\n');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed failed:', err);
    process.exit(1);
  }
};

seed();
